# Generated by Django 4.0.1 on 2022-04-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabChecker', '0002_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendees',
            name='file',
            field=models.FileField(upload_to='upload/'),
        ),
    ]
