# Generated by Django 4.0.1 on 2022-04-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabChecker', '0004_members_membersheetupload_remove_event_attendees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersheetupload',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
